// export const provincias = [
//     "Buenos Aires",
//     "Catamarca",
//     "Chaco",
//     "Chubut",
//     "CABA",
//     "Córdoba",
//     "Corrientes",
//     "Entre Ríos",
//     "Formosa",
//     "Jujuy",
//     "La Pampa",
//     "La Rioja",
//     "Mendoza",
//     "Misiones",
//     "Neuquén",
//     "Río Negro",
//     "Salta",
//     "San Juan",
//     "San Luis",
//     "Santa Cruz",
//     "Santa Fe",
//     "Santiago del Estero",
//     "Tierra del Fuego",
//     "Tucumán",
//   ];
  
//  export const localidades: { [key: string]: string[] } = {
//     "Buenos Aires": [
//       "La Plata",
//       "Mar del Plata",
//       "Bahía Blanca",
//       "Lomas de Zamora",
//       "Tigre",
//     ],
//     CABA: ["Buenos Aires"],
//     Córdoba: [
//       "Córdoba",
//       "Villa María",
//       "Río Cuarto",
//       "San Francisco",
//       "Alta Gracia",
//     ],
//     Catamarca: [
//       "San Fernando del Valle de Catamarca",
//       "Belén",
//       "Fiambalá",
//       "Chilecito",
//     ],
//     Chaco: ["Resistencia", "Charata", "Saenz Peña", "Pcia. Roque Sáenz Peña"],
//     Chubut: ["Rawson", "Comodoro Rivadavia", "Trelew", "Puerto Madryn"],
//     Corrientes: ["Corrientes", "Goya", "Mercedes", "Paso de los Libres"],
//     "Entre Ríos": ["Paraná", "Concordia", "Gualeguaychú", "Colón"],
//     Formosa: ["Formosa", "Clorinda", "El Colorado", "Pirané"],
//     Jujuy: ["San Salvador de Jujuy", "Palpalá", "Libertador General San Martín"],
//     "La Pampa": ["Santa Rosa", "General Pico", "Realicó"],
//     "La Rioja": ["La Rioja", "Chamical", "Chilecito"],
//     Mendoza: ["Mendoza", "San Rafael", "Malargüe", "Godoy Cruz"],
//     Misiones: ["Posadas", "Eldorado", "Oberá"],
//     Neuquén: [
//       "Neuquén",
//       "San Martín de los Andes",
//       "Caviahue",
//       "Villa La Angostura",
//     ],
//     "Río Negro": ["Viedma", "San Carlos de Bariloche", "General Roca"],
//     Salta: ["Salta", "Orán", "Tartagal"],
//     "San Juan": ["San Juan", "Jáchal", "Albardón"],
//     "San Luis": ["San Luis", "Villa Mercedes", "El Trapiche"],
//     "Santa Cruz": ["Río Gallegos", "El Calafate", "Caleta Olivia"],
//     "Santa Fe": ["Santa Fe", "Rosario", "Rafaela", "Venado Tuerto"],
//     "Santiago del Estero": [
//       "Santiago del Estero",
//       "La Banda",
//       "Termas de Río Hondo",
//     ],
//     "Tierra del Fuego": ["Ushuaia", "Río Grande", "Tolhuin"],
//     Tucumán: ["San Miguel de Tucumán", "Concepción", "Tafí Viejo"],
//   };